/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Duoc UC
 */
public class Listar extends javax.swing.JFrame {

    /**
     * @return the jConsulta2
     */
    public javax.swing.JRadioButton getjConsulta2() {
        return jConsulta2;
    }

    /**
     * @param jConsulta2 the jConsulta2 to set
     */
    public void setjConsulta2(javax.swing.JRadioButton jConsulta2) {
        this.jConsulta2 = jConsulta2;
    }

    /**
     * @return the jComentarios
     */
    public javax.swing.JLabel getjComentarios() {
        return jComentarios;
    }

    /**
     * @param jComentarios the jComentarios to set
     */
    public void setjComentarios(javax.swing.JLabel jComentarios) {
        this.jComentarios = jComentarios;
    }

    /**
     * @return the jConsulta1
     */
    public javax.swing.JRadioButton getjConsulta1() {
        return jConsulta1;
    }

    /**
     * @param jConsulta1 the jConsulta1 to set
     */
    public void setjConsulta1(javax.swing.JRadioButton jConsulta1) {
        this.jConsulta1 = jConsulta1;
    }

    /**
     * @return the jEjecutarConsulta
     */
    public javax.swing.JButton getjEjecutarConsulta() {
        return jEjecutarConsulta;
    }

    /**
     * @param jEjecutarConsulta the jEjecutarConsulta to set
     */
    public void setjEjecutarConsulta(javax.swing.JButton jEjecutarConsulta) {
        this.jEjecutarConsulta = jEjecutarConsulta;
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo_cine.png"));


        return retValue;
    }
    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMostrar = new javax.swing.JTable();
        jDepto = new javax.swing.JComboBox<>();
        jEjecutarConsulta = new javax.swing.JButton();
        jConsulta1 = new javax.swing.JRadioButton();
        jComentarios = new javax.swing.JLabel();
        jConsulta2 = new javax.swing.JRadioButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jAgregar = new javax.swing.JMenu();
        jListar = new javax.swing.JMenu();
        jEliminar = new javax.swing.JMenu();
        jModificar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TblMostrar.setFont(new java.awt.Font("Tahoma", 0, 9));
        TblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Rut","Nombre","Apellido", "Celular", "Email", "Sueldo Bruto", "Estado Civil", "Nombre Depto"
            }
        ));
        TblMostrar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        TblMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblMostrar.setRowHeight(13);
        jScrollPane1.setViewportView(TblMostrar);

        jDepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar Todos", "Informática", "Redes", "Administración", "Finanzas y Bienestar" }));

        jEjecutarConsulta.setText("Ejecutar Consulta");

        buttonGroup1.add(jConsulta1);
        jConsulta1.setText("1");

        jComentarios.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComentarios.setText(" ");

        buttonGroup1.add(jConsulta2);
        jConsulta2.setText("2");

        jAgregar.setText("Agregar");
        jMenuBar2.add(jAgregar);

        jListar.setText("Listar");
        jListar.setEnabled(false);
        jMenuBar2.add(jListar);

        jEliminar.setText("Eliminar");
        jMenuBar2.add(jEliminar);

        jModificar.setText("Modificar");
        jMenuBar2.add(jModificar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEjecutarConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jConsulta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jConsulta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEjecutarConsulta)
                    .addComponent(jConsulta1)
                    .addComponent(jConsulta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComentarios)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jAgregar;
    private javax.swing.JLabel jComentarios;
    private javax.swing.JRadioButton jConsulta1;
    private javax.swing.JRadioButton jConsulta2;
    private javax.swing.JComboBox<String> jDepto;
    private javax.swing.JButton jEjecutarConsulta;
    private javax.swing.JMenu jEliminar;
    private javax.swing.JMenu jListar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jModificar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TblMostrar
     */
    public javax.swing.JTable getTblMostrar() {
        return TblMostrar;
    }

    /**
     * @param TblMostrar the TblMostrar to set
     */
    public void setTblMostrar(javax.swing.JTable TblMostrar) {
        this.TblMostrar = TblMostrar;
    }

    /**
     * @return the jAgregar
     */
    public javax.swing.JMenu getjAgregar() {
        return jAgregar;
    }

    /**
     * @param jAgregar the jAgregar to set
     */
    public void setjAgregar(javax.swing.JMenu jAgregar) {
        this.jAgregar = jAgregar;
    }

    /**
     * @return the jEliminar
     */
    public javax.swing.JMenu getjEliminar() {
        return jEliminar;
    }

    /**
     * @param jEliminar the jEliminar to set
     */
    public void setjEliminar(javax.swing.JMenu jEliminar) {
        this.jEliminar = jEliminar;
    }

    /**
     * @return the jListar
     */
    public javax.swing.JMenu getjListar() {
        return jListar;
    }

    /**
     * @param jListar the jListar to set
     */
    public void setjListar(javax.swing.JMenu jListar) {
        this.jListar = jListar;
    }

    /**
     * @return the jMenuBar2
     */
    public javax.swing.JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    /**
     * @param jMenuBar2 the jMenuBar2 to set
     */
    public void setjMenuBar2(javax.swing.JMenuBar jMenuBar2) {
        this.jMenuBar2 = jMenuBar2;
    }

    /**
     * @return the jModificar
     */
    public javax.swing.JMenu getjModificar() {
        return jModificar;
    }

    /**
     * @param jModificar the jModificar to set
     */
    public void setjModificar(javax.swing.JMenu jModificar) {
        this.jModificar = jModificar;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    

    /**
     * @return the jDepto
     */
    public javax.swing.JComboBox<String> getjDepto() {
        return jDepto;
    }

    /**
     * @param jDepto the jDepto to set
     */
    public void setjDepto(javax.swing.JComboBox<String> jDepto) {
        this.jDepto = jDepto;
    }
}
